# Generated by Django 3.0.4 on 2020-03-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantestorneo',
            name='partid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participantestorneo',
            name='partjugadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participantestorneo',
            name='partpuntaje',
            field=models.IntegerField(null=True),
        ),
    ]
